---
title: Tables in Website
author: Hoas
date: '2019-02-12'
slug: tables-in-website
categories:
  - fragmentray
tags:
  - R
  - RMarkdown
  - HTML
lastmod: '2019-02-12T21:12:18+08:00'
keywords: [Tables in Website,R]
description: 'Tables in Website with R.'
comment: yes
toc: yes
autoCollapseToc: no
postMetaInFooter: yes
hiddenFromHomePage: no
contentCopyright: no
reward: no
mathjax: yes
mathjaxEnableSingleDollar: yes
mathjaxEnableAutoNumber: yes
hideHeaderAndFooter: no
---

<!--more-->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
require(knitr)
require(kableExtra)
require(DT)
library(htmlTable)
```

# [kableExtra](https://haozhu233.github.io/kableExtra/awesome_table_in_html_cn.html)

```{r echo=TRUE, message=FALSE, warning=FALSE}
knitr::kable(head(mtcars))

knitr::kable(head(mtcars)) %>%
  kable_styling(bootstrap_options = c("striped","hover","responsive")) %>%
  scroll_box(width = "500px", height = "200px")
```

# [DT](https://rstudio.github.io/DT/)

```{r echo=TRUE, message=FALSE, warning=FALSE}
datatable(iris, options = list(
  searching = FALSE,
  pageLength = 5,
  lengthMenu = c(5, 10, 15, 20)
))
```

# [htmlTable](https://cran.r-project.org/web/packages/htmlTable/vignettes/tables.html)

```{r}
output <- 
  matrix(paste("Content", LETTERS[1:16]), 
         ncol=4, byrow = TRUE)

htmlTable(output,
          header =  paste(c("1st", "2nd",
                            "3rd", "4th"), "header"),
          rnames = paste(c("1st", "2nd",
                           "3rd", "4th"), "row"),
          rgroup = c("Group A",
                     "Group B"),
          n.rgroup = c(2,2),
          cgroup = c("Cgroup 1", "Cgroup 2&dagger;"),
          n.cgroup = c(2,2), 
          caption="Basic table with both column spanners (groups) and row groups",
          tfoot="&dagger; A table footer commment")
```

